In [1]:
import pandas as pd

In [2]:
matches_df=pd.read_csv("matches.csv")

In [3]:
df1=matches_df[matches_df['toss_winner']==matches_df['winner']]

In [4]:
df1=df1.query("toss_decision=='field'")

In [5]:
df2=matches_df[matches_df['toss_winner']!=matches_df['winner']]

In [6]:
df2=df2.query("toss_decision=='bat'")

In [7]:
df=pd.concat([df1,df2])

In [9]:
players=df.groupby('player_of_match')

In [10]:
players.aggregate('count')

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,venue,umpire1,umpire2,umpire3
player_of_match,,,,,,,,,,,,,,,,,
A Kumble,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
A Mishra,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,1
A Nehra,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0
A Singh,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
AB Dinda,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
AB de Villiers,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,3
AC Gilchrist,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0
AD Mascarenhas,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
AD Russell,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,2
AJ Finch,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0
AJ Tye,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
AM Rahane,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,0
AR Patel,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
AS Yadav,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
AT Rayudu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,1
Azhar Mahmood,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
B Kumar,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
B Lee,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
B Stanlake,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
BA Stokes,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
BB McCullum,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
BJ Hodge,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0
BW Hilfenhaus,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
CA Lynn,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2
CH Gayle,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,0
CH Morris,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
CJ Anderson,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
CRD Fernando,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
DA Miller,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
DA Warner,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SK Raina,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0
SK Trivedi,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
SK Warne,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
SL Malinga,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1
SM Katich,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
SM Pollock,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
SP Goswami,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
SP Narine,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,2
SPD Smith,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1
SR Tendulkar,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0
SR Watson,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,3
SS Iyer,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1
ST Jayasuriya,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
SV Samson,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
SW Billings,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Sandeep Sharma,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,0
Shakib Al Hasan,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Sohail Tanvir,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
TL Suman,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
TM Dilshan,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
UT Yadav,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,2
Umar Gul,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
V Kohli,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,0
V Sehwag,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,0
VR Aaron,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1
WP Saha,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
YK Pathan,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,0
YS Chahal,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Yuvraj Singh,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Z Khan,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0

In [11]:
print("YK Pathan has won maximum number of MOM awards while chasing")

YK Pathan has won maximum number of MOM awards while chasing